version: 1.0.0-{build}
skip_tags: true
image: Ubuntu2004

environment:
  github_apikey:
    secure: otfsPx1BAgExY/kZkP2q79UlcBeM7N6dmOgb6ejiFgv0rYfrj4ceTVCE7hVqkf9q
  github_nuget_apikey:
    secure: REwHqDgDWHoujm/lBbXsBFrCh0+68E948v07bNmLCwYl1O8/9KghKN+114SLksUg
  docker_password:
    secure: 3BLFSWasBkoBDnePlBhgN0zzV0lRnmJ+BJ2WFEKHIKMt1f0j/CimHAZKFSzu9jvA
  octopus_apikey:
    secure: 0IgMHdGwSSfi8luQElPX8Uaq6YQoCATxDfj51hUFDpA=
  chart_pass:
    secure: 7tyr7himLkr10WLFocbJfA==
  sonar_token:
    secure: AjWsPrmfrPf3YS+bj5DEuBB/a4K/hKii8tJvN6TIn9+aCurkDx1f5SayNFJ0ZG3v

services:
  - docker

install:
  - ls compose | xargs -I {} docker-compose -f compose/{}/docker-compose.yml up -d
  - echo '======== es 8'
  - docker logs elasticsearch
  - echo '======== es 7'
  - docker logs elasticsearchlegacy
  - git clone -b develop --single-branch https://$github_apikey@github.com/insperex/TwoEightyCap.DevOps.Tools.git ~/tools
  - bash ~/tools/dist/shared/version.sh
  - bash ~/tools/dist/dotnet/install.sh
  - bash ~/tools/dist/dotnet/sonar.sh start $sonar_token

build_script: bash ~/tools/dist/dotnet/build.sh $github_nuget_apikey

test_script: 
  - bash ~/tools/dist/dotnet/test.sh

after_test: 
  - bash ~/tools/dist/dotnet/sonar.sh stop $sonar_token
  - bash ~/tools/dist/dotnet/publish_nuget.sh $github_nuget_apikey
  
deploy_script: 
 - bash ~/tools/dist/shared/publish_docker.sh $docker_password out
 - bash ~/tools/dist/shared/publish_helm.sh $octopus_apikey $chart_pass

artifacts:
  - path: 'artifacts\**\*.nupkg'
    name: nuget-package
